### ISSUE TITLE
UpdatedTasks

### ISSUE THREAD

**Issue by AndrewMitev** [TeamCastle/Fitness-Manager#7]
Team “Castle” Tasks
 Клас: “User”, “FatUser”, интерфейс: “FatLossSchedule”
o Андрей Митев
 Клас: “StrengthUser”, интерфейс: “StrengthGainSchedule”
o Ивайло Паскалев
 Клас: “Rookie”, интерфейс: “RookieSchedule”
o Натали Петкова
 Клас: “Exercise”, “UpperBody”, “Biceps”
o Веселин Петков
 Клас: “Triceps”, “Chest”, “Back”
o Мирослав Василев
 Клас: “Abs”, “Shoulders”, “Traps”; “LowerBody”
o Иванка Зайчева
 Клас: “Calves”, “FrontLegs”, “BackLegs”
o Станислав Илиев
 Клас: “Feeding”, “RookiesNutritions”; интерфейс:
“FeedRoockies”
o Симеон Чолаков
 Клас: “FattiesNutritions”, “StrengthNutritions”, интерфейси:
“FeedFatties”, “FeedStrong”
o Лилия Маркова

Основна идея: Създаване на приложение за съставяне на тренировчна
програма. Всеки потребител се логва (username, password) избира
програма: дали тепърва започва да се занимава с фитнес – “Rookie”, дали
иска да отслабне – “FatUser”, дали иска да натрупа маса – “StrengthUser”.
При “Rookie” приложението съставя само график на провеждане на
тренировките през седмицата, колко време да траят, какви упражнения,
кои мускули да се тренират съответния ден, по колко серии и колко
повторения. Съставя хранителен режим, като също така съставя
предпоръчителен прием на калории (можем да добавим съвети какви
храни да се консумират и т.н. Нещата са отоворени за развитие).

Пример:
User – име и парола;
FatUser – индекс процент мазнини, сърдечен ритъм, брой килограми за
сваляне.
FatLossSchedule:
1. TrainMonday()
 TrainUpperBody() -> в него се създават инстанции на Exercise и
наследници, целта е да си видят кои мускули и с какви упражнения
се тренират и т.н; DailyFoodConsumption() – инстанция на Feeding
2. TrainTuesday() -> …

**Comment by simoto** [comment]
many difference with the implementation
